version: "3.3"

services:
  backend:
    build:
      context: ./server-express
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    restart: unless-stopped
    volumes:
      - ./server-express/node_modules:/usr/app/node_modules
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./node_modules:/usr/app/node_modules
      - .:/usr/app